DROP TABLE IF EXISTS CLIENTES CASCADE;
DROP TABLE IF EXISTS RESTAURANTES CASCADE;
DROP TABLE IF EXISTS PEDIDOS CASCADE;
DROP TABLE IF EXISTS ENTREGADORES CASCADE;
DROP TABLE IF EXISTS ENTREGA_PEDIDO;

DROP TYPE IF EXISTS ped_status;
DROP TYPE IF EXISTS ent_veic;

CREATE TABLE CLIENTES(
    ClienteID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomeC VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL,
    Cidade VARCHAR(20),

    CONSTRAINT email_uniq UNIQUE (Email)
);

CREATE TABLE RESTAURANTES(
    RestauranteID INTEGER GENERATED ALWAYS AS IDENTITY,
    NomeR VARCHAR(20) NOT NULL,
    Categoria VARCHAR(20) NOT NULL,
    TaxaEntrega NUMERIC(4,2),

    CONSTRAINT rest_pk PRIMARY KEY (RestauranteID),
    CONSTRAINT nome_r_uniq UNIQUE (NomeR)
);

CREATE TYPE ped_status AS ENUM(
    'Recebido', 'Em preparo', 'Entregue', 'Cancelado'
);

CREATE TABLE PEDIDOS(
    PedidoID INTEGER GENERATED ALWAYS AS IDENTITY,
    ClienteID INTEGER NOT NULL,
    RestID INTEGER NOT NULL,
    DATA_PED DATE NOT NULL,
    STATUS_PED ped_status,
    Valor NUMERIC(5,2),

    CONSTRAINT pedidos_pk PRIMARY KEY (PedidoID),
    CONSTRAINT pedidos_sk UNIQUE (ClienteID, RestID, DATA_PED),
    CONSTRAINT ped_fk_cli FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ped_fk_res FOREIGN KEY (RestID) REFERENCES RESTAURANTES(RestauranteID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TYPE ent_veic AS ENUM(
    'Moto', 'Bicicleta', 'Carro'
);

CREATE TABLE ENTREGADORES(
    EntregadorID INTEGER GENERATED ALWAYS AS IDENTITY,
    NomeE VARCHAR(20) NOT NULL,
    Veiculo ent_veic NOT NULL,
    Placa VARCHAR(7),

    CONSTRAINT ent_pk PRIMARY KEY (EntregadorID),
    CONSTRAINT ent_nome_uniq UNIQUE (NomeE),
    CONSTRAINT ent_placa_check CHECK(Veiculo = 'Bicicleta' OR Placa IS NOT NULL)
);

CREATE TABLE ENTREGA_PEDIDO(
    PedidoID INTEGER,
    EntregadorID INTEGER,
    DataEntrega DATE NOT NULL,

    CONSTRAINT entrega_ped_pk PRIMARY KEY (PedidoID, EntregadorID),
    CONSTRAINT ent_ped_fk_ped FOREIGN KEY (PedidoID) REFERENCES PEDIDOS(PedidoID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ent_ped_fk_ent FOREIGN KEY (EntregadorID) REFERENCES ENTREGADORES(EntregadorID)
        ON DELETE CASCADE ON UPDATE CASCADE
);