DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS GUIA;
DROP TABLE IF EXISTS PESQUISADOR;
DROP TABLE IF EXISTS BASE_OPERACIONAL;
DROP TABLE IF EXISTS EXPEDICAO;

CREATE TABLE PESSOA(
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(11)
);

CREATE TYPE guia_certif AS ENUM(
    'Iniciante',
    'Intermediario',
    'Experiente'
);

CREATE TABLE GUIA(
    CPF VARCHAR(11) PRIMARY KEY,
    CERTIFICACAO guia_certif,

    CONSTRAINT guia_fk_pessoa
        FOREIGN KEY CPF REFERENCES PESSOA(CPF)
);

CREATE TYPE pesq_esp AS ENUM(
    'Biologia',
    'Geologia',
    'Arqueologia',
    'Paleontologia',
    'Antropologia',
);

CREATE TABLE GUIA(
    CPF VARCHAR(11) PRIMARY KEY,
    CERTIFICACAO pesq_esp,

    CONSTRAINT guia_fk_pessoa
        FOREIGN KEY CPF REFERENCES PESSOA(CPF)
);

CREATE TABLE BASE_OPERACIONAL(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100),
    LOCALIZACAO VARCHAR (100)
);

CREATE TYPE nivel_diff AS ENUM(
    'Facil',
    'Medio',
    'Dificil'
);

CREATE TABLE EXPEDICAO(
    ID_EXPEDICAO GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR(20),
    NIVEL_DIFICULDADE nivel_diff,
    ID_BASE INTEGER NOT NULL,
    CPF_GUIA VARCHAR(11) UNIQUE NOT NULL,

    CONSTRAINT exped_fk_base
        FOREIGN KEY ID_BASE REFERENCES BASE_OPERACIONAL(ID),
        
    CONSTRAINT exped_fk_guia
        FOREIGN KEY CPF_GUIA REFERENCES GUIA(CPF),
);


