DROP TABLE IF EXISTS ATUA;
DROP TABLE IF EXISTS PONTO_OBSERVACAO;
DROP TABLE IF EXISTS PARTICIPACAO;
DROP TABLE IF EXISTS EXPEDICAO CASCADE;
DROP TABLE IF EXISTS ESTACAO CASCADE;
DROP TABLE IF EXISTS BASE_OPERACIONAL CASCADE;
DROP TABLE IF EXISTS PESQUISADOR CASCADE;
DROP TABLE IF EXISTS GUIA CASCADE;
DROP TABLE IF EXISTS PESSOA CASCADE;

DROP TYPE IF EXISTS guia_certif;
DROP TYPE IF EXISTS pesq_esp;
DROP TYPE IF EXISTS nivel_diff;
DROP TYPE IF EXISTS tipo_est;

CREATE TABLE PESSOA(
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(11)
);

CREATE TYPE guia_certif AS ENUM(
    'Iniciante',
    'Intermediario',
    'Experiente'
);

CREATE TABLE GUIA(
    CPF VARCHAR(11) PRIMARY KEY,
    CERTIFICACAO guia_certif,

    CONSTRAINT guia_fk_pessoa 
        FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
            ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TYPE pesq_esp AS ENUM(
    'Biologia',
    'Geologia',
    'Arqueologia',
    'Paleontologia',
    'Antropologia'
);

CREATE TABLE PESQUISADOR(
    CPF VARCHAR(11) PRIMARY KEY,
    CERTIFICACAO pesq_esp,

    CONSTRAINT pesq_fk_pessoa 
        FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
            ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BASE_OPERACIONAL(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100),
    LOCALIZACAO VARCHAR (100)
);

CREATE TYPE nivel_diff AS ENUM(
    'Facil',
    'Medio',
    'Dificil'
);

CREATE TABLE EXPEDICAO(
    ID_EXPEDICAO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR(20),
    NIVEL_DIFICULDADE nivel_diff,
    ID_BASE INTEGER NOT NULL,
    CPF_GUIA VARCHAR(11) UNIQUE NOT NULL,

    CONSTRAINT exped_fk_base
        FOREIGN KEY (ID_BASE) REFERENCES BASE_OPERACIONAL(ID)
            ON UPDATE CASCADE,
        
    CONSTRAINT exped_fk_guia
        FOREIGN KEY (CPF_GUIA) REFERENCES GUIA(CPF)
            ON UPDATE CASCADE
);

CREATE TABLE PARTICIPACAO(
    CPF_PESSOA VARCHAR(11),
    ID_EXPEDICAO INTEGER,
    DATA_PARTICIPACAO DATE,

    PRIMARY KEY (CPF_PESSOA, ID_EXPEDICAO),

    CONSTRAINT part_fk_pess
        FOREIGN KEY (CPF_PESSOA) REFERENCES PESSOA(CPF),
            ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT part_fk_exp
        FOREIGN KEY (ID_EXPEDICAO) REFERENCES EXPEDICAO(ID_EXPEDICAO)
            ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE PONTO_OBSERVACAO(
    ID_EXPEDICAO INTEGER,
    NUMERO INTEGER,
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION,

    PRIMARY KEY (ID_EXPEDICAO, NUMERO),

    CONSTRAINT po_fk_exp
        FOREIGN KEY (ID_EXPEDICAO) REFERENCES EXPEDICAO(ID_EXPEDICAO)
            ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TYPE tipo_est AS ENUM(
    'Descanso',
    'Pesquisa',
    'Reabastecimento'
);

CREATE TABLE ESTACAO(
    ID_ESTACAO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO tipo_est,
    DESCRICAO VARCHAR(50)
);

CREATE TABLE ATUA(
    CPF_PESQUISADOR VARCHAR(11),
    ID_EXPEDICAO INTEGER,
    ID_ESTACAO INTEGER,
    RELATORIO VARCHAR(300),

    PRIMARY KEY (CPF_PESQUISADOR, ID_EXPEDICAO, ID_ESTACAO),

    CONSTRAINT atua_fk_pesq
        FOREIGN KEY (CPF_PESQUISADOR) REFERENCES PESQUISADOR(CPF)
            ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT atua_fk_exp
        FOREIGN KEY (ID_EXPEDICAO) REFERENCES EXPEDICAO(ID_EXPEDICAO),
            ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT atua_fk_est
        FOREIGN KEY (ID_ESTACAO) REFERENCES ESTACAO(ID_ESTACAO)
            ON DELETE CASCADE ON UPDATE CASCADE,
);